name: CI pipeline
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -race -coverpkg=./... ./... -coverprofile cover.out.tmp -covermode=atomic
      - name: Removes mocks from tests
        run: cat cover.out.tmp | grep -v "_mock.go" > cover.out
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31
          args: --skip-files .*_test.go
      - uses: codecov/codecov-action@v1
        with:
          file: ./cover.out
      - name: Update codecov
        run: bash <(curl -s https://codecov.io/bash)
